django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('',
         TemplateView.as_view(template_name="home.html"),
         name="home"),
    path('team',
         TemplateView.as_view(template_name="team.html"),
         name="team"),
    path('about',
         TemplateView.as_view(template_name="about.html"),
         name="about"),
    path('user_anly',
         TemplateView.as_view(template_name="user_anly.html"),
         name="user_anly"),
    path('ui_design',
         TemplateView.as_view(template_name="ui_design.html"),
         name="ui_design"),
    path('wireframe_page',
         TemplateView.as_view(template_name="wireframe_page.html"),
         name="wireframe_page"),
    path('user_flow_page',
         TemplateView.as_view(template_name="user_flow_page.html"),
         name="user_flow_page"),
    path('A',
         TemplateView.as_view(template_name="A perweb.html"),
         name="A"),
    path('B',
         TemplateView.as_view(template_name="B perweb.html"),
         name="B"),
    path('C',
         TemplateView.as_view(template_name="C perweb.html"),
         name="C"),
    path('D',
         TemplateView.as_view(template_name="D perweb.html"),
         name="D"),
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += staticfiles_urlpatterns()

users/urls.py
"""Accounts app URL Configuration."""
from django.urls import path
from .views import SignUpView

app_name = 'users'
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

users/models.py
"""Accounts models."""
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _

from .managers import CustomUserManager


class CustomUser(AbstractUser):
    """Custom User class."""

    username = None
    email = models.EmailField(_('email address'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        """Return email as the object's string representation."""
        return self.email

users/forms.py
"""Forms for accounts app."""
from django import forms
from .models import CustomUser
from django.contrib.auth.forms import (UserCreationForm, UserChangeForm)


class CustomUserCreationForm(UserCreationForm):
    """Registration form."""

    class Meta:
        """Meta class."""

        model = CustomUser
        fields = ("first_name", "last_name", "email", "password1", "password2")
        widgets = {
            'first_name': forms.TextInput(attrs={"class": "form-control"}),
            'last_name': forms.TextInput(attrs={"class": "form-control"}),
            'email': forms.TextInput(attrs={"class": "form-control"}),
            'password1': forms.TextInput(attrs={"class": "form-control"}),
            'password2': forms.TextInput(attrs={"class": "form-control"}),
        }


class CustomUserChangeForm(UserChangeForm):
    """User profile change view."""

    class Meta:
        """Meta class."""

        model = CustomUser
        fields = ('email',)

users/views.py
"""Accounts view."""
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUpView(generic.CreateView):
    """Registration view."""

    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

templates/A perweb.html
{% extends "base_generic.html" %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/contact.css' %}">
{% endblock %}

{% block title %} &starf; Andrew &starf; {% endblock %}

{% block content %}
<style>
    .myDiv {
        width: 800px;
        height: 200px;
        position: absolute;
        margin: auto;
        left: 0;
        right: 0;
        top: 0;
        bottom: 0;
    }
    </style>
<div><h5>Name: Andrew</h5>
    <h5>User type: Admin</h5>
    <h5>Occupation: Computer Scientist/Mathematician</h5>
</div>
<div class=myDiv>
    <h5>User Scenario: </h5>
    <p>Scenario 1: Andrew uses the app to refine equations and add new ones to allow the other users a better and more versatile experience.
    </p>
    <p>Scenario 2: Andrew uses the app to design a user-frienly UI to make the average user's experience more convenient.
        </p>
    <br>
    <br>
    <h5>User Stories:</h5>
    <p>Story 1: As a mathematician, I want to make sure that everyone who uses the app gains access to accurate and precise calculations they can rely on as well as having a plethora of different equations that suit their needs.
        </p> 
    <p>Story 2: As a computer scientist, I want to make the user's experience on the app easy and reliable by providing a frieldy UI that clearly labels everything a user would need while accessing the app and making calculations.
        </p>
</div>
{% endblock %}

templates/B perweb.html
{% extends "base_generic.html" %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/contact.css' %}">
{% endblock %}

{% block title %} &spades; Harrison &spades; {% endblock %}

{% block content %}
<style>
    .myDiv {
        margin: 100px;
        left: 0;
        right: 0;
        top: 0;
        bottom: 0;
    }
</style>

<div class="container">
    <h5>Name: Harrison</h5>
    <h5>User type: Regular</h5>
    <h5>Occupation: Athlete</h5>
</div>

<div class="container myDiv">
    <h5>User Scenario: </h5>
    <p>Scenario 1: Harrison is attempting to lose weight consistently for better performance in his sport by a certain day. He uses Everything Calculator to precisely measure how much weight per week / month to achieve goal on time.</p>
    <p>Scenario 2: Harrison also needs assistance counting the specific calorie amount in each meal. Everything Calculator will assist with this as well.</p>
    <br>
    <br>
    <h5>User Stories:</h5>
    <p>Story 1: As an athlete, I need to lose 25 pounds by the end of the summer (3 months from current time in scenario), to improve performance.</p>
    <p>Story 2: As an athlete, I need to maintain a cetain weight for boxing and want to have the exact calorie count of each meal.</p>
</div>
{% endblock %}

templates/C perweb.html
{% extends "base_generic.html" %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/contact.css' %}">
{% endblock %}

{% block title %} &hearts; Penny &hearts; {% endblock %}

{% block content %}
<style>
    .myDiv {
        width: 800px;
        height: 200px;
        position: absolute;
        margin: auto;
        left: 0;
        right: 0;
        top: 0;
        bottom: 0;
    }
    </style>
<div><h5>Name: Penny</h5>
    <h5>User type: Regular</h5>
    <h5>Occupation: Worker/General Public</h5>
</div>
<div class=myDiv>
    <h5>User Scenario: </h5>
    <p>Scenario 1: Penny uses the app to calculate how much she should save per paycheck in the span of five months in order to afford a Nintendo Switch for her family member by Christmas.
    </p>
    <p>Scenario 2: Penny uses the app to calculate how much she should tip the waiter at the restaurant using a choice-base percentage and the total amount from the meal.
        </p>
    <br>
    <br>
    <h5>User Stories:</h5>
    <p>Story 1: As a worker, I want to make sure I am saving at least the minimum amount per month in order to purchase an item in a set amount of time.
        </p> 
    <p>Story 2: As a part of the general public, I want an easy way to calculate tip percentage to pay my waiter.
        </p>
</div>
{% endblock %}

templates/D perweb.html
{% extends "base_generic.html" %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/contact.css' %}">
{% endblock %}

{% block title %} &diams; Kim &diams; {% endblock %}

{% block content %}
<style>
    .myDiv {
        margin: 100px;
        left: 0;
        right: 0;
        top: 0;
        bottom: 0;
    }
</style>

<div class="container">
    <h5>Name: Kim</h5>
    <h5>User type: Regular</h5>
    <h5>Occupation: College Student/General Public</h5>
</div>

<div class="container myDiv">
    <h5>User Scenario: </h5>
    <p>Scenario 1: Kim uses the app to gain a better understanding of how problems are solved. She does not find her current resources (teacher, notes, etc.) to be helpful, and would like a step-by-step explanation of the problem solving process.</p>
    <p>Scenario 2: Kim uses the app to check her homework. Doing calculus problems can be a time-consuming process, which means that checking your work can take a bit of time as well. Kim uses this app after solving a problem to check if she computed the correct answer or not. This way, she can immediately move on to the next problem if an answer is correct.</p>
    <br>
    <br>
    <h5>User Stories:</h5>
    <p>Story 1: As a student, I need a way for complex processes and information to be simplified and explained in a way that I can understand.</p>
    <p>Story 2: As a student, I want a way to easily check my work and see if my answers are correct.</p>
</div>
{% endblock %}

templates/about.html
{% extends "base_generic.html" %}

{% block title %}About Everything Calculator{% endblock %}

{% block content %}

<div class="container">
    <p>Everything Calculator is a handy app that can perform a wide variety of calculations. From complex math equations to calorie intake to tips to budgeting, this calculator assists with it all. As a general purpose, multi-functional calculator, Everything Calculator is a tool that anyone can find a use for.</p>
    <p>On the subject of math, Everything Calculator can assist you with calculus, geometry, algebra, trigonometry, and more. If interested in dieting or calorie consumption, this app can provide guidance on the amount of calories needed to lose, gain, or maintain weight. At a restaurant with friends and trying to figure out how much to leave as a tip or how to split the bill? Everything Calculator has functions for that, too. Trying to save money for something? Use the app to figure out how much money you should put away each week or month. These, along with many more functions, make Everything Calculator an extremely handy tool for a variety of everyday activities.</p>
</div>

<div>
    <h5>Vision Statement</h5>
    <p>For high school students, college students, workout enthusiasts, and the general public who are in need of
    mathematical calculation help, Everything Calculator is a multi-purpose calculator app that allows users to calculate
    many different types of math-based problems. Unlike sites like Wolfram Alpha, our product allows users to calculate
    more than just math problems, such as dietary calculations, weight loss calculations, and tip/financial calculations. </p>
</div>

<div>
    <h5>Expected Users</h5>
    <p>Our target audience for Everything Calculator are high school to college level students, those who need help with dietary
    calculations (caloric intake, weight tracking, etc.), or those who need quick and simple calculations done (tips, basic math, etc.)</p>
</div>

<div>
    <h5>User Benefits</h5>
    <p>Our users will gain access to a general use calculator for basic calculations (addition, subtraction, etc.), more advanced
    mathematical options (calculus, algebra, geometry, etc.), tip and financial calculators, and health tracking calculators
    (daily/weekly/monthly caloric intake, weight loss calculations, etc.). </p>
</div>
{% endblock %}

templates/base_generic.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel='icon' href='favicon.ico' type='image/x-icon' sizes="16x16" />
    <meta charset="utf-8">
    <title>Everything Calculator</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Everything Calculator"> 
    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    {# Display django.contrib.messages as Bootstrap alerts #}
    {% bootstrap_messages %}

    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    {% block style %} {% endblock %}
</head>

<body>
    {% include "navbar.html" %}
    <div class="container">
        <h1 align="center">{% block title %}{% endblock %}</h1>
        <div class="row">
            {% block content %}{% endblock %}
        </div>
    </div>
    {% include "footer.html" %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</body>
</html>

templates/footer.html
<footer class="footer text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p>
            Everything Calculator is powered by
            <a target="_blank" href="https://getbootstrap.com/">Bootstrap 4</a>
            and <a target="_blank" href="https://fontawesome.com/">Font awesome</a>.
            Please customize it for yourself!
        </p>
    </div>
</footer>

templates/home.html
{% extends "base_generic.html" %}
{% load static %}

{% block content %}
<style>
    /* Modify the background color */
     
    .button-custom {
        background-color: #8CC1B2;}
    .button-custom1 {
        background-color: #97D7C5;}
    </style>
<main role="main">
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-3">
                The Everything Calculator
                <img src="{% static 'img/product_icon.png' %}" alt="icon" style="width:125px;height:125px;"/>
            </h1>
            <p>General use calculator to utilize for everyday activities.</p>
            <p>
                <a class="btn button-custom1 btn-lg" href="{% url 'about' %}" role="button">
                Learn more &raquo;</a>
            </p>
            </div>
    </div>

    <div class="container">
        <img src="{% static 'img/product_icon.png' %}" alt="icon" />
    </div>

    <div class="container">
        <div class="box">
            <img src="{% static 'img/product_icon.png' %}" alt="icon" />
        </div>
    </div>

    <div class="container">
        <!-- Example row of columns -->
        <div class="row">
            On the subject of math, the Everything Calculator can assist you with calculus, geometry, algebra, trigonometry, and more. If interested in dieting or calorie consumption, this app can provide guidance on the amount of calories needed to lose, gain, or maintain weight. At a restaurant with friends and trying to figure out how much to leave as a tip or how to split the bill? Everything Calculator has functions for that, too. Trying to save money for something? Use the app to figure out how much money you should put away each week or month.
            These, along with many more functions, make Everything Calculator an extremely handy tool for a variety of everyday activities.
        </div>
    </div>
</main>
{% endblock %}

templates/navbar.html
<style>
    /* Modify the background color */
     
    .navbar-custom {
        background-color: #8CC1B2;}
    </style>
<nav class="navbar navbar-expand-md navbar-dark fixed-top navbar-custom">
    <a class="navbar-brand" href="{% url 'home' %}">
        <i class="fas fa-calculator"></i> Everything Calculator
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse">
        <ul class="navbar-nav  mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">
                    <i class="fas fa-sitemap"></i> About
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'team' %}">
                    <i class="fas fa-address-card"></i> Team
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user_anly' %}">
                    <i class="fas fa-clipboard-user"></i> User Analysis
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'ui_design' %}">
                    <i class="fas fa-clipboard-user"></i> UI Design
                </a>
            </li>
        </ul>
        <ul class="navbar-nav my-2 my-lg-0">
        {% if user.is_authenticated %}
            <li class="nav-item">
                <span class="navbar-text">
                    <i class="fas fa-user-shield"></i> {{ user.email }}
                </span>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'password_change' %}">
                    <i class="fas fa-user-cog"></i> Change password
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">
                    <i class="fas fa-sign-out-alt"></i> Log out
                </a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">
                    <i class="fas fa-sign-in"></i> Sign in
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:signup' %}">
                    <i class="fas fa-user-edit"></i> Sign up
                </a>
            </li>
        {% endif %}
        </ul>
    </div>
</nav>

templates/team.html
{% extends "base_generic.html" %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/contact.css' %}">
{% endblock %}

{% block title %} Meet our team {% endblock %}

{% block content %}
<div class="container mt-40">
    <div class="row mt-30">
        <div class="col-md-3 col-sm-6">
            <div class="box15">
                <img src="{% static 'img/user_icon_a.png' %}" alt="user" />
                <div class="box-content">
                    <h3 class="title">Austin</h3>
                    <ul class="icon">
                        <li><a href="#"><i class="fab fa-linkedin"></i></a></li>
                        <li><a href="#"><i class="fab fa-gitlab"></i></a></li>
                    </ul>
                </div>
            </div>
            <span class="post">Team Lead (Team Member A)</span>
        </div>
        <div class="col-md-3 col-sm-6">
            <div class="box15">
                <img src="{% static 'img/user_icon_b.png' %}" alt="user" />
                <div class="box-content">
                    <h3 class="title">Ryan</h3>
                    <ul class="icon">
                        <li><a href="#"><i class="fab fa-linkedin"></i></a></li>
                        <li><a href="#"><i class="fab fa-gitlab"></i></a></li>
                    </ul>
                </div>
            </div>
            <span class="post">Team Member B</span>
        </div>
        <div class="col-md-3 col-sm-6">
            <div class="box15">
                <img src="{% static 'img/user_icon_c.png' %}" alt="user" />
                <div class="box-content">
                    <h3 class="title">Milan</h3>
                    <ul class="icon">
                        <li><a href="#"><i class="fab fa-linkedin"></i></a></li>
                        <li><a href="#"><i class="fab fa-gitlab"></i></a></li>
                    </ul>
                </div>
            </div>
            <span class="post">Team Member C</span>
        </div>
        <div class="col-md-3 col-sm-6">
            <div class="box15">
                <img src="{% static 'img/user_icon_d.png' %}" alt="user" />
                <div class="box-content">
                    <h3 class="title">Caroline</h3>
                    <ul class="icon">
                        <li><a href="#"><i class="fab fa-linkedin"></i></a></li>
                        <li><a href="#"><i class="fab fa-gitlab"></i></a></li>
                    </ul>
                </div>
            </div>
            <span class="post">Team Member D</span>
        </div>
    </div>
</div>
{% endblock %}

templates/ui_design.html
{% extends "base_generic.html" %}

{% block title %}UI Design{% endblock %}

{% block content %}
<style>
    /* Modify the background color */
    .button-custom1 {
        background-color: #97D7C5;}
    .myDiv {
        text-align: center;}
</style>

<div class="container">
    <p class="myDiv">
        <a class="btn button-custom1 btn-lg" href="{% url 'wireframe_page' %}" role="button">
            Wireframes</a> &emsp;
        <a class="btn button-custom1 btn-lg" href="{% url 'user_flow_page' %}" role="button">
            User Flow Diagram</a> &emsp;
    </p>
</div>
{% endblock %}

templates/user_anly.html
{% extends "base_generic.html" %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/contact.css' %}">
{% endblock %}

{% block title %} User Analysis {% endblock %}

{% block content %}
<style>
    /* Modify the background color */
    .button-custom1 {
        background-color: #97D7C5;}
</style>

<div class="container">
    <h3> User Segments</h3>
    <p> There are two types of users for this app: regular and admin</p>
    <ul>
        <li><p> Regular user -  can use the app</p></li>
        <li><p> Admin user - can use <em>and</em> edit the app</p></li>
    </ul>
</div>

<div class="container">
     <h3>User Stories</h3>
     <p>Here's a list of links to our user's webpages:</p>
     <p>
        <a class="btn button-custom1 btn-lg" href="{% url 'A' %}" role="button">
            Andrew</a> &emsp;
        <a class="btn button-custom1 btn-lg" href="{% url 'B' %}" role="button">
            Harrison</a> &emsp;
        <a class="btn button-custom1 btn-lg" href="{% url 'C' %}" role="button">
            Penny</a> &emsp;
        <a class="btn button-custom1 btn-lg" href="{% url 'D' %}" role="button">
            Kim</a> &emsp;
    </p>
</div>

<div class="container">
     <h3>Features</h3>
     <ul>
         <li><p> General Calculator for basic math</p></li>
         <li><p> Advanced Math Calculator for calculus, differential equations, matrices, and more</p></li>
         <li><p> Calculator for science and equation based calculations</p></li>
         <li><p> Tip calculator</p></li>
         <li><p> Weight tracker</p></li>
         <li><p> Diet calculator for portion sizes</p></li>
         <li><p> Day/Week/Month caloric tracker/calculator</p></li>
         <li><p> Savings/Budgeting calculator</p></li>
         <li><p> Access to history of calculations (weight loss, calories lost, previous math problems solved, etc.)</p></li>
         <li><p> Customizable profile picture</p></li>
         <li><p> Separate tabs for each type of calculator</p></li>
    </ul>
</div>
{% endblock %}

templates/user_flow_page.html
{% extends "base_generic.html" %}
{% load static %}
<head>
{% block title %}User Flow Diagram{% endblock %}
</head>
{% block content %}
<style>
    /* Modify the background color */
    .button-custom1 {
        background-color: #97D7C5;}
    .myDiv {
        text-align: center;}
    .buttonAlignment {
        margin-left: 0px;
        margin-top: 0px;}
</style>

<div class="container">
    <div>
        <a class="btn button-custom1 btn-lg buttonAlignment" href="{% url 'ui_design' %}" role="button">
            Back</a> &emsp;
    </div>
    <div class="myDiv">
        <img src="{% static 'img/cat.jpg' %}" alt="cat" style="width:600px;height:600px;">
    </div>
</div>
{% endblock %}

templates/wireframe_page.html
{% extends "base_generic.html" %}
{% load static %}
<head>
{% block title %}Wireframes{% endblock %}
</head>
{% block content %}
<style>
    /* Modify the background color */
    .button-custom1 {
        background-color: #97D7C5;}
    .myDiv {
        text-align: center;}
    .buttonAlignment {
        margin-left: 0px;
        margin-top: 0px;}
</style>

<div class="container">
    <div>
        <a class="btn button-custom1 btn-lg buttonAlignment" href="{% url 'ui_design' %}" role="button">
            Back</a> &emsp;
    </div>
    <div class="myDiv">
        <img src="{% static 'wf-imgs/Home Page.jpg' %}" alt="homepg"/>
        <img src="{% static 'wf-imgs/About_Page.png' %}" alt="aboutpg"/>
        <img src="{% static 'wf-imgs/Basic_Calculator_Page.png' %}" alt="basicpg"/>
        <img src="{% static 'wf-imgs/Basic_Calculator_After_Result.png' %}" alt="basicARpg"/>
        <img src="{% static 'wf-imgs/Advanced_Calculator_Page.png' %}" alt="advpg"/>
        <img src="{% static 'wf-imgs/Advanced_Calculator_After_Result.png' %}" alt="advARpg"/>
        <img src="{% static 'wf-imgs/Tip_Calculator_After_Result.png' %}" alt="tippg"/>
        <img src="{% static 'wf-imgs/Finance.png' %}" alt="finpg"/>
        <img src="{% static 'wf-imgs/weight.png' %}" alt="weightpg"/>
        <img src="{% static 'wf-imgs/Profile-Login.png' %}" alt="prfLpg"/>
        <img src="{% static 'wf-imgs/Profile-Register.png' %}" alt="prfRpg"/>    
    
    </div>
</div>
{% endblock %}